Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AllCops:
  Exclude:
    - /**/*.jbuilder
    - config/unicorn.rb
    - config/spring.rb
    - config/puma.rb
    - config/initializers/devise.rb
    - config/initializers/wrap_parameters.rb
    - config/initializers/backtrace_silencers.rb
    - config/initializers/content_security_policy.rb
    - db/**/*
    - bin/**/*
    - node_modules/**/*
    - test/**/*
  Rails:
    Enabled: true
